import type { Metadata } from 'next'
import type { AppRootState } from '@/interfaces/common.interface'

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Montserrat } from 'next/font/google'
import '@/assets/css/globals.scss'

const montserrat = Montserrat({ weight: '400', style: ['normal'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = async ({ children, params: { lang } }: Readonly<AppRootState>) => {
  return (
    <html lang={lang}>
      <body className={montserrat.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>{children}</AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayout
